services:

  active_mq:
    image: apache/activemq-artemis:latest-alpine
    container_name: rabbitmq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ARTEMIS_USER=mq
      - ARTEMIS_PASSWORD=mq


  admin-service-db:
    image: mysql:8.2.0-oracle
    container_name: admin-db
    ports:
      - "3380:3306"
    volumes:
      - "mysql_admin:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always

  voting-service-db:
    image: mysql:8.2.0-oracle
    container_name: voting-db
    ports:
      - "3381:3306"
    volumes:
      - "mysql_voting:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always

  loki:
    image: grafana/loki:2.8.2
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki

volumes:
  mysql_admin:
  mysql_voting:

networks:
  loki:

