#Paranmétrage applicatif de base
spring:
  application:
    name: api-gateway
server:
  port: 9999
#Paramétrage avec eureka discovery
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#Paramétrage des endpoints actuator
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
