services:

  service-registry:
    build:
      context: ../service-registry
      dockerfile: ../service-registry/Dockerfile
    image: service-registry
    environment:
      - SERVER_PORT=8761
    ports:
      - 8761:8761
    networks:
      - voting-app

  admin-service:
    container_name: admin-service
    build:
      context: ../admin-service
      dockerfile: ../admin-service/Dockerfile
    image: admin-service
    environment:
      - ACTIVEMQ_URI=tcp://active-mq:61616
      - SERVER_PORT=8080
      - MYSQL_DB=jdbc:mysql://admin-db:3306/admin-service?createDatabaseIfNotExist=true
      - EUREKA_URI=http://service-registry:8761/eureka
      - SPRING_PROFILES_ACTIVE=mysql
    ports:
      - 8880:8080
    networks:
      - voting-app
    depends_on:
      - active-mq
      - admin-service-db
      - service-registry

  voting-service:
    container_name: voting-service
    build:
      context: ../voting-service
      dockerfile: ../voting-service/Dockerfile
    image: voting-service
    environment:
      - ACTIVEMQ_URI=tcp://active-mq:61616
      - ADMIN_SERVICE_URI=http://admin-service:8880
      - SERVER_PORT=8081
      - MYSQL_DB=jdbc:mysql://voting-db:3306/voting-service?createDatabaseIfNotExist=true
      - EUREKA_URI=http://service-registry:8761/eureka
      - SPRING_PROFILES_ACTIVE=mysql
    ports:
      - 8881:8081
    networks:
      - voting-app
    depends_on:
      - active-mq
      - voting-service-db
      - service-registry

  active-mq:
    image: apache/activemq-artemis:latest-alpine
    container_name: active-mq
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      - ARTEMIS_USER=mq
      - ARTEMIS_PASSWORD=mq
    networks:
      - voting-app

  admin-service-db:
    image: mysql:8.2.0-oracle
    container_name: admin-db
    ports:
      - "3380:3306"
    volumes:
      - "mysql_admin:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    networks:
      - voting-app

  voting-service-db:
    image: mysql:8.2.0-oracle
    container_name: voting-db
    ports:
      - "3381:3306"
    volumes:
      - "mysql_voting:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    networks:
      - voting-app

volumes:
  mysql_admin:
  mysql_voting:

networks:
  voting-app:
    driver: bridge
